name: Prevent scheduled workflow from being automatically disabled
# Ref: https://myscreate.com/prevent-scheduled-workflow-from-being-automatically-disabled/

on:
  schedule:
    # 毎月4,19日の14:45（UTC）に実行
    - cron: "45 14 4,19 * *"
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: false

jobs:

  keepalive:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:

      - name: Re-enable workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh workflow enable enable_workflow.yml
          gh workflow enable daily.yml
